export interface TopicStat { topic: string; percentage: number; trend: 'up' | 'down' | 'flat'; }
export interface LanguageStat { language: string; solved: number; }
export interface ActivityDay { date: string; count: number; }
export type TopicStrength = 'strong' | 'average' | 'weak';
export interface TopicPerformance { topicId: string; topicName: string; attempted: number; solved: number; strengthScore: number; strength: TopicStrength; aiInsight: string | null; }
export interface DifficultyBreakdown { easy: number; medium: number; hard: number; }
export interface DifficultyTotals { easy: number; medium: number; hard: number; }
export interface SuccessRateDataPoint { label: string; successRate: number; solved: number; }
export interface RecentSubmission { submissionId: string; problemId: string; problemTitle: string; difficulty: 'Easy' | 'Medium' | 'Hard'; status: 'Accepted' | 'Wrong Answer' | 'Runtime Error' | 'Time Limit Exceeded'; language: string; submittedAt: string; }
export interface ProgressRecommendedProblem { problemId: string; title: string; difficulty: 'Easy' | 'Medium' | 'Hard'; topic: string; reason: string; }
export interface HintUsageStats { totalHintsUsed: number; averageHintsPerProblem: number; solvedWithZeroHints: number; solvedUsingAllHints: number; }
export interface DailyActivity { date: string; submitted: boolean; }
export interface StreakData { currentStreak: number; longestStreak: number; lastSevenDays: DailyActivity[]; }
export interface ProgressSummary { studentName: string; totalAttempted: number; totalSolved: number; successRate: number; streak: StreakData; }
export interface StudentAnalytics { summary: ProgressSummary; topics: TopicPerformance[]; difficultyBreakdown: DifficultyBreakdown; successRateHistory: SuccessRateDataPoint[]; recentSubmissions: RecentSubmission[]; recommendations: ProgressRecommendedProblem[]; hintUsage: HintUsageStats; }
export interface PublicProfileData { user: { username: string; name: string; avatarInitials: string; role: 'student' | 'instructor'; joinedAt: string; headline?: string; bio?: string; social?: { linkedin?: string; github?: string; twitter?: string; }; }; totalSolved: number; totalAttempted: number; successRate: number; streak: { currentStreak: number; longestStreak: number; totalActiveDays: number; totalSubmissionsLastYear: number; }; difficultyBreakdown: DifficultyBreakdown; difficultyTotals: DifficultyTotals; languageStats: LanguageStat[]; topicStats: TopicPerformance[]; activityGrid: ActivityDay[]; recentAccepted: RecentSubmission[]; }
export const MOCK_ANALYTICS: StudentAnalytics = { summary: { studentName: 'Mohamed', totalAttempted: 47, totalSolved: 31, successRate: 66, streak: { currentStreak: 7, longestStreak: 15, lastSevenDays: [{ date: '2025-07-17', submitted: true }, { date: '2025-07-18', submitted: true }, { date: '2025-07-19', submitted: false }, { date: '2025-07-20', submitted: true }, { date: '2025-07-21', submitted: true }, { date: '2025-07-22', submitted: true }, { date: '2025-07-23', submitted: true }] } }, topics: [{ topicId: 't1', topicName: 'Arrays', attempted: 12, solved: 10, strengthScore: 83, strength: 'strong', aiInsight: null }, { topicId: 't2', topicName: 'Strings', attempted: 8, solved: 6, strengthScore: 75, strength: 'strong', aiInsight: null }, { topicId: 't3', topicName: 'Hashing', attempted: 5, solved: 3, strengthScore: 60, strength: 'average', aiInsight: null }, { topicId: 't4', topicName: 'Sorting', attempted: 4, solved: 2, strengthScore: 50, strength: 'average', aiInsight: null }, { topicId: 't5', topicName: 'Dynamic Programming', attempted: 7, solved: 2, strengthScore: 28, strength: 'weak', aiInsight: 'Focus on memoization.' }, { topicId: 't6', topicName: 'Recursion', attempted: 5, solved: 2, strengthScore: 35, strength: 'weak', aiInsight: 'Define base cases first.' }, { topicId: 't7', topicName: 'Graphs', attempted: 3, solved: 1, strengthScore: 33, strength: 'weak', aiInsight: 'Review BFS vs DFS.' }, { topicId: 't8', topicName: 'Trees', attempted: 3, solved: 2, strengthScore: 66, strength: 'average', aiInsight: null }], difficultyBreakdown: { easy: 18, medium: 10, hard: 3 }, successRateHistory: [{ label: 'Mon', successRate: 50, solved: 2 }, { label: 'Tue', successRate: 66, solved: 4 }, { label: 'Wed', successRate: 60, solved: 3 }, { label: 'Thu', successRate: 75, solved: 6 }, { label: 'Fri', successRate: 80, solved: 4 }, { label: 'Sat', successRate: 0, solved: 0 }, { label: 'Sun', successRate: 100, solved: 5 }], recentSubmissions: [{ submissionId: 's1', problemId: 'p1', problemTitle: 'Two Sum', difficulty: 'Easy', status: 'Accepted', language: 'Python', submittedAt: '2025-07-23T10:30:00Z' }], recommendations: [{ problemId: 'r1', title: 'Coin Change', difficulty: 'Medium', topic: 'Dynamic Programming', reason: 'Weakness area' }], hintUsage: { totalHintsUsed: 14, averageHintsPerProblem: 0.9, solvedWithZeroHints: 18, solvedUsingAllHints: 3 } };
export interface DashboardSummary { problemsSolved: number; avgScore: number; streak: number; totalAttempts: number; acceptanceRate: number; hintsUsedToday: number; hintsLimit: number; }
export interface WeeklyActivity { date: string; solved: number; attempted: number; }
export interface ScorePoint { date: string; score: number; }
export interface RecommendedProblem { id: string; title: string; difficulty: 'easy' | 'medium' | 'hard'; topic: string; topicLabel: string; reason: string; estimatedMinutes: number; }
export interface StudentDashboardData { summary: DashboardSummary; topicStats: TopicStat[]; weeklyActivity: WeeklyActivity[]; scoreHistory: ScorePoint[]; recommendations: RecommendedProblem[]; }